"""
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻:
Write a python program that will take input from the person, their name and 
profession. Your program should create a nested dictionary where the 
profession will be the key of the first dictionary and an unique ID 
generated by the program should be the key of the nested dictionary where 
you will store the name of that person as value.
ID Generation formula: inputNo_LastName_FirstThreeLetterOfProfession

If the person’s name contains only one word, consider that as the last 
name. Assume all the input will be given in capital letters and take input 
until the user gives “END” as input. Finally print the dictionary. No need 
to follow the format, just print the dictionary.

Sample Input:

NARUTO UZUMAKI ENGINEER
JAMES HAMISH WATSON DOCTOR
TANJIRO ENGINEER
SAUL GOODMAN LAWYER
EREN YEAGER DOCTOR
END

Sample Output:
{
'ENGINEER': {
'1_UZUMAKI_ENG': 'NARUTO UZUMAKI',
  '3_TANJIRO_ENG': 'TANJIRO'
},
'DOCTOR': {
'2_WATSON_DOC': 'JAMES HAMISH WATSON', '
5_YEAGER_DOC': 'EREN YEAGER'
},
'LAWYER': {'4_GOODMAN_LAW': 'SAUL GOODMAN'}
}
"""
count=0
ans={}
while(True):
    inp=input()
    if inp=="END":
        print(ans)
        break
    else:
        count=count+1
        inp=inp.split()
        
        id = str(count)+"_"+inp[-2]+"_"+inp[-1][:3]
        nameP=' '.join(map(str, inp[:len(inp)-1]))
        
        if inp[-1] not in ans:
            ans[inp[-1]]={id:nameP}
            
        else:
            ans[inp[-1]][id]=nameP